In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
f=pd.array([1,2,3,4,5])
f

<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64

In [4]:
f=pd.Series([1,2,3,4,5,6])
f

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
# convert pandas to list
box=[]

for i in f:
    box.append(i)
print(box)

print(type(box))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [7]:
# covert pandas to list

ds=pd.Series([1,2,3,4,5])
print(ds)
print(type(ds))

print("Convert pandas to list")
d_list=ds.tolist()
print(d_list,type(d_list))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
Convert pandas to list
[1, 2, 3, 4, 5] <class 'list'>


In [10]:
g=np.array([1,2,3,4,5])

In [11]:
type(g)

numpy.ndarray

In [13]:
g.tolist()

[1, 2, 3, 4, 5]

In [19]:
# pandas program to add,substract,multiply, divide two series

a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])

print("Add two Series\n-----------------\n",a+b,
      "\nSubstract two Series\n------------\n",a-b,
      "\nMultiply Two Series\n-------------------------\n",a*b,
      "\nDivide two Series\n------------------\n",a/b)

Add two Series
-----------------
 0     3
1     7
2    11
3    15
4    19
dtype: int64 
Substract two Series
------------
 0    1
1    1
2    1
3    1
4    1
dtype: int64 
Multiply Two Series
-------------------------
 0     2
1    12
2    30
3    56
4    90
dtype: int64 
Divide two Series
------------------
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [22]:
# compare the elements of two Pandas Series
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,10])

print("A is greater then B\n-----------\n",a>b)
print("B is less then A\n--------------\n",a<b)
print("A is equal to B\n--------------\n",a==b)
print("A is not equal to B\n----------\n",a!=b)

A is greater then B
-----------
 0     True
1     True
2     True
3     True
4    False
dtype: bool
B is less then A
--------------
 0    False
1    False
2    False
3    False
4    False
dtype: bool
A is equal to B
--------------
 0    False
1    False
2    False
3    False
4     True
dtype: bool
A is not equal to B
----------
 0     True
1     True
2     True
3     True
4    False
dtype: bool


In [24]:
# Convert Pandas Program to Convert a dictionary to a Pandas series
print("Original Dictinary")
f={'a':100,'b':200,'c':300,'d':400,'e':800}
new_Series=pd.Series(data=f)

Original Dictinary


In [25]:
print(new_Series)

a    100
b    200
c    300
d    400
e    800
dtype: int64


In [26]:
# convert a NumpY array to a Pandas Series
p=np.array([1,2,3,4,5])
print(type(p))

<class 'numpy.ndarray'>


In [27]:
ds=pd.Series(data=p)
print(type(ds))

<class 'pandas.core.series.Series'>


In [28]:
ds

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [35]:
# Pandas Program to change the data type of a column or a Series
x=pd.Series(['100',300,'Python',300.12,'400'])
df=pd.Series(data=x,dtype=float)
df

0       100
1       300
2    Python
3    300.12
4       400
dtype: object

In [36]:
print("Change the said data type to Numeric:")
s2=pd.to_numeric(df,errors='coerce')
print(s2)

Change the said data type to Numeric:
0    100.00
1    300.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [39]:
# write a Pandas Program to convert the first column of a Data Frame as a Series
f=pd.DataFrame(data={"Col1":[1,2,3,4,7,11],"Col2":[4,5,6,9,5,0],"Col3":[7,5,8,12,1,11]})
pd.Series(data=f['Col1'])

0     1
1     2
2     3
3     4
4     7
5    11
Name: Col1, dtype: int64

In [41]:
# iloc all rows and 1 column
s1=f.iloc[:,0]
s1

0     1
1     2
2     3
3     4
4     7
5    11
Name: Col1, dtype: int64

In [43]:
# Write a Pandas to convert a given Series to an array

f=pd.Series([100,200,'python','300.12',400])
g=pd.array(f)

In [44]:
type(g)

pandas.core.arrays.numpy_.PandasArray

In [45]:
f.values

array([100, 200, 'python', '300.12', 400], dtype=object)

In [46]:
g.value_counts

<bound method NDArrayBackedExtensionArray.value_counts of <PandasArray>
[100, 200, 'python', '300.12', 400]
Length: 5, dtype: object>

In [48]:
print(type(a))

<class 'pandas.core.series.Series'>


In [62]:
# Pandas Program to convert Series of lists to one Series
a=['Red','Green','White']
b=['Red','Black']
c=['Yellow']

f=pd.Series([
    ['Red','Green','White'],
['Red','Black'],
['Yellow']])
f

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [55]:
ds=pd.Series(data=[a,b,c])

In [63]:
print("Original Series of List")
print(f)

s=f.apply(pd.Series).stack().reset_index(drop=True)
print(s)


Original Series of List
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [78]:
# pandas Program to sort a given Series

# old Series
f=pd.Series(data=['100','2','3','Python','300.12','400'])
print("Original Data Series:")
print(f)

Original Data Series:
0       100
1         2
2         3
3    Python
4    300.12
5       400
dtype: object


In [79]:
# New Series
pd.Series(f).sort_values()

0       100
1         2
2         3
4    300.12
5       400
3    Python
dtype: object

In [80]:
# Write Pandas Program to add some data to an existing Series
print("Original Data Series:")
s=pd.Series(data=[100,200,'Python',300.12,400])
s

Original Data Series:


0       100
1       200
2    Python
3    300.12
4       400
dtype: object

In [86]:
print("\nData Series after adding some data:")
new_s=pd.concat([s,pd.Series(['php'])],ignore_index=True)
new_s


Data Series after adding some data:


0       100
1       200
2    Python
3    300.12
4       400
5       php
dtype: object

In [87]:
# Write a Pandas Program to create a subset of a given series based on values and condition 

s=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)

print("SUbset of the above given Series:")
n=6
new_s=s[s>n]
new_s

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
SUbset of the above given Series:


7      7
8      8
9      9
10    10
dtype: int64

In [91]:
# write a Pandas Program to change the order of index of given series

data_series=pd.Series(data=[1,2,3,4,5],index=['A','B','C','D','E'])
print("Original Data Series")
print(data_series)

# changing the oder of the index

new_data_series=data_series.reindex(index=['B',"A",'C','D','E'])
print("Data Series after changing the order of Index")
new_data_series


Original Data Series
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of Index


B    2
A    1
C    3
D    4
E    5
dtype: int64

In [93]:
# write a Pandas Program to create the mean and std deviation of the data of a given series
ds=pd.Series([1,2,3,4,5])
print("Original Data Series")
print(ds)

print("Data Series Mean",ds.mean())
print("Data Series STD",ds.std())

Original Data Series
0    1
1    2
2    3
3    4
4    5
dtype: int64
Data Series Mean 3.0
Data Series STD 1.5811388300841898


In [98]:
# write  Pandas program to get the items of a given series not present in another given series
sr1=pd.Series(data=[1,2,3,4,5])
print("Data Series 1\n",sr1)
sr2=pd.Series(data=[2,4,6,8,10])
print("Data Series 2\n",sr2)

print("Checking Items that are not Present in another given Series")
result=sr1[~sr1.isin(sr2)]
result

Data Series 1
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Data Series 2
 0     2
1     4
2     6
3     8
4    10
dtype: int64
Checking Items that are not Present in another given Series


0    1
2    3
4    5
dtype: int64

In [102]:
# will show is in 
sr1[sr1.isin(sr2)]

1    2
3    4
dtype: int64

In [103]:
sr1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [104]:
sr2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [105]:
sr1[~sr1.isin(sr2)]

0    1
2    3
4    5
dtype: int64

In [115]:
# find 25 th percentile,50th percentile and 75th percentile and max

data_ser=pd.Series(data=np.random.randint(10,30,6)
                  )
print(data_ser)
data_ser.quantile([0.25])

0    18
1    19
2    26
3    22
4    25
5    10
dtype: int32


0.25    18.25
dtype: float64

In [117]:
pd.Series(data=np.percentile(data_ser,[0,25,50,75,100]))

0    10.00
1    18.25
2    20.50
3    24.25
4    26.00
dtype: float64

In [120]:
# calculate the frequency of unique values of a given series
ds=pd.Series(data=np.random.randint(0,10,20))
print("ds= ",)

print("Checking the Unique count Frequency")
ds.value_counts()

ds= 
Checking the Unique count Frequency


3    5
0    4
4    3
7    3
8    2
2    1
5    1
1    1
dtype: int64

In [124]:
num_ser=pd.Series(np.take(list('0123456789'),np.random.randint(10,size=40)))
print("Original number")
print(num_ser)

print("Frequency of Unique Counts")
num_ser.value_counts()

Original number
0     2
1     7
2     6
3     2
4     4
5     4
6     9
7     0
8     9
9     4
10    1
11    7
12    5
13    8
14    8
15    7
16    1
17    8
18    6
19    8
20    9
21    1
22    5
23    5
24    1
25    3
26    1
27    7
28    0
29    7
30    2
31    1
32    0
33    1
34    5
35    9
36    9
37    2
38    5
39    5
dtype: object
Frequency of Unique Counts


1    7
5    6
7    5
9    5
2    4
8    4
4    3
0    3
6    2
3    1
dtype: int64

In [127]:
# Write a pandas program to display most frequent values in a given series and replace everything else as 'Other' in the series

num_series=pd.Series(data=np.random.randint(1,5,[15]))
num_series

0     3
1     3
2     4
3     1
4     3
5     4
6     4
7     1
8     1
9     1
10    4
11    4
12    1
13    4
14    1
dtype: int32

In [130]:
num_series.unique()

array([3, 4, 1])

In [131]:
print("Most frequent item")
num_series.value_counts()

Most frequent item


4    6
1    6
3    3
dtype: int64

In [136]:
num_series[~num_series.isin(num_series.value_counts().index[:1])]='Other'

In [137]:
num_series

0     Other
1     Other
2         4
3     Other
4     Other
5         4
6         4
7     Other
8     Other
9     Other
10        4
11        4
12    Other
13        4
14    Other
dtype: object

In [148]:
num_series[:3]

0    Other
1    Other
2        4
dtype: object

In [149]:
# write Pandas Program to find the positions of numbers that are multiple of 5 of a given series
num_ser=pd.Series(np.arange(4,11))
num_ser

0     4
1     5
2     6
3     7
4     8
5     9
6    10
dtype: int32

In [152]:
result=np.where(num_ser%5==0)
print("Position of Numbers that are multiple of 5:")
result

Position of Numbers that are multiple of 5:


(array([1, 6], dtype=int64),)

In [153]:
num_ser[1]

5

In [154]:
np.arange(0,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
# write a Pandas Program to extract items at given positions of a given series
s=pd.Series(np.random.randint(0,5,9))
s

0    0
1    1
2    1
3    0
4    3
5    4
6    4
7    2
8    3
dtype: int32

In [158]:
element_pos=[0,2,6,7]
result=s.take(element_pos)

print("Extract the position of the given Number")
print(result)

Extract the position of the given Number
0    0
2    1
6    4
7    2
dtype: int32


In [162]:
# write a pandas Program to conver the First and Last character of each word as capitalise

f=pd.Series(data=['php','java','python','c#'])
f

0       php
1      java
2    python
3        c#
dtype: object

In [177]:
result=f.map(lambda x:x[0].upper()+x[1:-1]+x[-1].upper())
result

0       PhP
1      JavA
2    PythoN
3        C#
dtype: object

In [187]:
# write a Pandas Program to compute difference of differences between consecutive numbers of a given series
ser=pd.Series(data=[1,3,8,10,11,15])
print("Original Number")
print(ser.tolist())

Original Number
[1, 3, 8, 10, 11, 15]


In [184]:
print("Difference of Differences between consecutive numbers of the said series:")
print(ser.diff().tolist())

Difference of Differences between consecutive numbers of the said series:
[nan, 2.0, 5.0, 2.0, 1.0, 4.0]


In [186]:
ser.diff().diff().tolist()

[nan, nan, 3.0, -3.0, -1.0, 3.0]

In [190]:
# write a Pandas program to convert a series of date strings to a time series.

day_series=pd.Series(data=['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
day_series

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [191]:
time_ser=pd.to_datetime(day_series)

In [192]:
time_ser

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [198]:
# write a Pandas Program to convert year-month string to dates adding a specified day of the month.
from dateutil.parser import parse
date_series=pd.Series(data=['Mar 2015','Feb 2016','Mar 2017','Apr 2018','May 2019'])
print("Original Series")
print(date_series)

result=date_series.map(lambda d: parse((input("Enter the Day"))+d))
result

Original Series
0    Mar 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object
Enter the Day12
Enter the Day14
Enter the Day15
Enter the Day17
Enter the Day18


0   2015-03-12
1   2016-02-14
2   2017-03-15
3   2018-04-17
4   2019-05-18
dtype: datetime64[ns]

In [199]:
# Write a Pandas program to filter words from a given series that contain atleast two vowels
from collections import Counter 
ser=pd.Series(data=['Red','Green','Orange','Pink','Yellow','White'])
print("Original Series")
print(ser)

Original Series
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object


In [202]:
print("Filtered Words")
result=ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')]))>=2
ser[result]

Filtered Words


1     Green
2    Orange
4    Yellow
5     White
dtype: object

In [207]:
# calculate Euclidean Distance
x=pd.Series(np.arange(1,12))
print(x.tolist())

y=pd.Series([11,10,9,8,7,6,5,4,3,2,1])
print(y.tolist())

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [208]:
# will calculate the Eclidean distance
np.linalg.norm(x-y)

20.97617696340303

In [ ]:
# Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series
nums=pd.Series([1,8,7,5,6,5,3,4,7,1])
print("Original Series:")
print(nums)
print("\nPositions of the values surrounded by smaller values on both sides: ")
temp=np.diff(np.sign(np.diff(nums)))
resul 